[tool.poetry]
name = "creating_blockchain"
version = "0.1.0"
description = ""
authors = [""]
readme = ""

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
